### ISSUE TITLE
Proper attribution

### ISSUE THREAD

**Issue by jrosebr1** [AshwinRaikar88/Blinky#1]
Hi @AshwinRaikar88, Adrian Rosebrock here from PyImageSearch.com.

If you are going to use my code for blink detection/liveness detection, kindly cite it properly. Your code from @rishikksh20 was actually based on my tutorials:

https://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/
https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/

It appears that @rishikksh20 did not properly cite the work either.

You can find how to properly cite my tutorials here:

https://www.pyimagesearch.com/faqs/single-faq/how-do-i-reference-or-cite-one-of-your-blog-posts-books-or-courses

Thank you for your attention in this matter.

**Comment by AshwinRaikar88** [comment]
Soo Happy to hear from you
I apologize for this egregious mistake, I honestly didn't know the source
of this code for liveliness detection.

I'll rectify the mistake and correct it to include the proper citation.

Also Thankyou soo much for this amazing blogpost and implementation on
liveliness detection.
There's a lot to learn, Thanks for making Computer Vision open and fun
to learn !!!!

**Comment by AshwinRaikar88** [comment]
My implementation uses only the eye blink detection so only the https://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/ link has been cited.

Thank you for your implementation.

The issue has been resolved.

**Comment by jrosebr1** [comment]
Thank you @AshwinRaikar88! 😄
